# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: ab604
day_night: false
font: UoS

# use an embedded font-family
# serif options: Fraunces / EB Garamond / Bitter
# sans-serif options: Commissioner / Alegreya Sans / Metropolis
# if you import your own fonts, name them here too
#customtextFontFamily: "Atkinson-Hyperlegible"
# custom_theme: "octaevo-hex"
#customheadingFontFamily = "Petrona"
# alternatively, leave empty and select basic font options: sans-serif or serif
# for more http://tachyons.io/docs/typography/font-family/
textFontFamily: "sans-serif"
headingFontFamily: "sans-serif"


# SEO

#site_type: Person
#local_business_type: ''
#org_name: ''
#description: ''
#twitter: ''

# Contact (edit or remove options as required)
email: bln1[at]soton.ac.uk
address:
  street: Building 85, Life Sciences, University of Southampton
  city: Southampton
  region: Hampshire
  postcode: 'SO17 1BJ'
  country: United Kingdom
  country_code: GB
coordinates:
  latitude: '50.93645'
  longitude: '-1.39534'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: false
  show_language: false
  show_day_night: false
  show_search: false
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-gb

# Site features

highlight: true
highlight_languages:
  - r
  - python
  - latex
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: false
  page: false
  post: false
  project: true
  publication: true
  event: false
reading_time: false
section_pager: false
docs_section_pager: true
sharing: true
# copyright_license:
#   enable: false
#   allow_derivatives: false
#   share_alike: true
#   allow_commercial: false
#   notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
# comments:
#   provider: ''
#   commentable:
#     post: true
#     book: true
#     project: true
#     publication: true
#     event: true
#   disqus:
#     shortname: ''
#     show_count: true
#   commento:
#     url: ''
# search:
#   provider: wowchemy
#   algolia:
#     app_id: ''
#     api_key: ''
#     index_name: ''
#     show_logo: false
map:
  provider: mapnik
  api_key: ''
#   zoom: 15
# marketing:
#   google_analytics: ''
#   google_tag_manager: ''
#   google_site_verification: ''
#   baidu_site_verification: ''
#   baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true
